# Generated by Django 3.2.12 on 2022-06-03 11:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Actualizado em')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('medicall', models.CharField(blank=True, choices=[('Medical Exam', 'Medical Exam')], max_length=50, null=True)),
                ('validate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Validade')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_employeers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_employeers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('type_document', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=14)),
                ('value', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsControlUssd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('trasantion_type', models.CharField(max_length=150)),
                ('amout', models.CharField(default='0', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsControlUssdMercados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('trasantion_type', models.CharField(max_length=150)),
                ('amout', models.CharField(default='0', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('codmercado', models.CharField(default='01', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('plano1', models.IntegerField(blank=True, null=True)),
                ('plano2', models.IntegerField(blank=True, null=True)),
                ('plano3', models.IntegerField(blank=True, null=True)),
                ('plano4', models.IntegerField(blank=True, null=True)),
                ('plano5', models.IntegerField(blank=True, null=True)),
                ('plano6', models.IntegerField(blank=True, null=True)),
                ('plano7', models.IntegerField(blank=True, null=True)),
                ('plano8', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Perguntas')),
                ('yes', models.IntegerField(blank=True, null=True)),
                ('no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestControlUssd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('trasantion_type', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='RequestsUssd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('trasantion_type', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date(2022, 6, 3))),
            ],
        ),
        migrations.CreateModel(
            name='Taximota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao')),
                ('valor_fixo', models.FloatField(default=315)),
                ('valor_pago', models.FloatField()),
                ('data_pagamento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som_id', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude1', models.CharField(max_length=100)),
                ('longitude1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Actualizado em')),
                ('formacao', models.CharField(choices=[('Folklift Operation VOC', 'Folklift Operation VOC'), ('Folklift Operation', 'Folklift Operation'), ('Light Duty Vehicle', 'Light Duty Vehicle'), ('Light Duty Vehicle VOC', 'Light Duty Vehicle VOC'), ('Telehandler Operation', 'Telehandler Operation'), ('Work at Height', 'Work at Height'), ('Work at Height VOC', 'Work at Height VOC'), ('LOTO', 'LOTO'), ('Confined Spaces ', 'Confined Spaces'), ('Confined Spaces VOC', 'Confined Spaces VOC'), ('Skid Steer Loader VOC', 'Skid Steer Loader VOC'), ('Cherry Picker VOC', 'Cherry Picker VOC'), ('Full Induction', 'Full Induction'), ('2h Induction', '2h Induction'), ('Overhead Crane VOC', 'Overhead Crane VOC'), ('Permit-to-Work', 'Permit-to-Work'), ('Tractor VOC', 'Tractor VOC'), ('Chemical Products', 'Chemical Products'), ('Firefighting', 'Firefighting'), ('Basic Firefighting', 'Basic Firefighting')], max_length=300)),
                ('validity', models.DateField(default=datetime.date.today, verbose_name='Validade')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_formations', to=settings.AUTH_USER_MODEL)),
                ('trabalhador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trabalhador', to='vm_formacao.employeer')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
